"use client"; // Mark as Client Component for AOS

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { useEffect } from "react";
import AOS from "aos";
import "aos/dist/aos.css"; // Import AOS styles
import "./globals.css";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

const metadata: Metadata = {
  title: "CodeMac",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  useEffect(() => {
    AOS.init({
      duration: 1000, // Animation duration in milliseconds
      once: true, // Animations trigger only once
      easing: "ease-out", // Smooth easing for animations
      mirror: false, // Prevent animations when scrolling up
    });

    // Refresh AOS on route changes
    AOS.refresh();

    // Cleanup (optional, resets AOS on unmount)
    return () => {
      AOS.refreshHard();
    };
  }, []);

  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
        <div className="border-t border-gray-300 bg-gray-900"></div>
        <Footer />
      </body>
    </html>
  );
}